export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/search/index',
    'pages/test/index',
    'pages/test/result',
    'pages/product/detail',
    'pages/customize/index',
    'pages/cart/index',
    'pages/order/confirm',
    'pages/coupon/index',
    'pages/message/index',
    'pages/agreement/user',
    'pages/agreement/privacy',
    'pages/profile/index',
    'pages/profile/orders',
    'pages/profile/records',
  ],
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#FFFFFF',
    navigationBarTitleText: '华烨尚医',
    navigationBarTextStyle: 'black',
    backgroundColor: '#FFFFFF',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#C9B78F',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: './assets/tabbar/home.png',
        selectedIconPath: './assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/customize/index',
        text: '全部商品',
        iconPath: './assets/tabbar/customize.png',
        selectedIconPath: './assets/tabbar/customize-active.png',
      },
      {
        pagePath: 'pages/cart/index',
        text: '购物车',
        iconPath: './assets/tabbar/customize.png',
        selectedIconPath: './assets/tabbar/customize-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: './assets/tabbar/user.png',
        selectedIconPath: './assets/tabbar/user-active.png',
      },
    ],
  },
})
